version: '3'
services:
  portainer:
    privileged: true
    image: portainer/portainer
    volumes:
    - ~/.docker/machine/machines/default:/certs
    ports:
    - "9100:9100"
    command: -p :9100 -H tcp://192.168.99.100:2376 --tlsverify
  docker-rm:
    privileged: true
    build: ./docker-rm
    ports:
    - "8081:8081"
    volumes:
    - ~/.docker/machine/machines/default:/opt/dockercerts
    - ./opt/rm/config:/opt/rm/config
    - ./opt/rm/logs:/opt/rm/logs
    - ./opt/csars:/opt/rm/csars
    environment:
    - DOCKER_HOST=tcp://192.168.99.100:2376
    - DOCKER_TLS_VERIFY=1
    - DOCKER_CERT_PATH=/opt/dockercerts
    - DOCKER_MACHINE_NAME=default

